[run]
watch_all = true
watch_dirs = ["cmd", "pkg"]
watch_exts = [".go"]
ignore = [".git", "docs", "assets", "templates", "node_modules"]
ignore_files = []
build_delay = 1500
interrupt_timout = 15
graceful_kill = false

init_cmds = [
  ["make", "build"],
  [
    "./oauth2-proxy",
    "--log-level",
    "debug",
    "server",
    "--assets-path",
    "assets/",
    "--templates-path",
    "templates/"
  ]
]

cmds = [
  ["make", "build"],
  [
    "./oauth2-proxy",
    "--log-level",
    "debug",
    "server",
    "--assets-path",
    "assets/",
    "--templates-path",
    "templates/"
  ]
]
