[run]
watch_all = true
watch_dirs = ["cmd", "pkg"]
watch_exts = [".go"]
ignore = [".git", "node_modules", "assets", "templates"]
ignore_files = []
build_delay = 1500
interrupt_timout = 15
graceful_kill = false

init_cmds = [
  ["make", "build"],
  ["./oauth2-proxy", "--debug", "server", "--templates", "templates/"]
]

cmds = [
  ["make", "build"],
  ["./oauth2-proxy", "--debug", "server", "--templates", "templates/"]
]
