workspace:
  base: /srv/app
  path: src/github.com/webhippie/oauth2-proxy

branches:
  - master

pipeline:
  cache-restore:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    restore: true
    when:
      local: false

  frontend-prepare:
    image: webhippie/nodejs:latest
    pull: true
    commands:
      - yarn install --frozen-lockfile

  frontend-lint:
    image: webhippie/nodejs:latest
    pull: true
    group: frontend
    commands:
      - yarn lint

  frontend-test:
    image: webhippie/nodejs:latest
    pull: true
    group: frontend
    commands:
      - yarn test

  frontend-build:
    image: webhippie/nodejs:latest
    pull: true
    group: frontend
    commands:
      - yarn build

  backend-prepare:
    image: webhippie/golang:edge
    pull: true
    environment:
      - CGO_ENABLED=0
      - GOPATH=/srv/app
      - TAGS=
    commands:
      - make clean
      - make retool
      - make sync
      - make generate

  backend-vet:
    image: webhippie/golang:edge
    pull: true
    group: backend
    environment:
      - CGO_ENABLED=0
      - GOPATH=/srv/app
      - TAGS=
    commands:
      - make vet

  backend-check:
    image: webhippie/golang:edge
    pull: true
    group: backend
    environment:
      - CGO_ENABLED=0
      - GOPATH=/srv/app
      - TAGS=
    commands:
      - make megacheck

  backend-lint:
    image: webhippie/golang:edge
    pull: true
    group: backend
    environment:
      - CGO_ENABLED=0
      - GOPATH=/srv/app
      - TAGS=
    commands:
      - make lint

  backend-test:
    image: webhippie/golang:edge
    pull: true
    group: backend
    environment:
      - CGO_ENABLED=0
      - GOPATH=/srv/app
      - TAGS=
    commands:
      - make test

  backend-build:
    image: webhippie/golang:edge
    pull: true
    group: backend
    environment:
      - CGO_ENABLED=0
      - GOPATH=/srv/app
      - TAGS=
    commands:
      - make build

  backend-linux:
    image: karalabe/xgo-latest:latest
    pull: true
    group: release
    environment:
      - CGO_ENABLED=0
      - GOPATH=/srv/app
      - TAGS=
    commands:
      - make release-dirs release-linux
    when:
      event: [ push, tag, pull_request ]

  backend-darwin:
    image: karalabe/xgo-latest:latest
    pull: true
    group: release
    environment:
      - CGO_ENABLED=0
      - GOPATH=/srv/app
      - TAGS=
    commands:
      - make release-dirs release-darwin
    when:
      event: [ push, tag ]

  backend-windows:
    image: karalabe/xgo-latest:latest
    pull: true
    group: release
    environment:
      - CGO_ENABLED=0
      - GOPATH=/srv/app
      - TAGS=
    commands:
      - make release-dirs release-windows
    when:
      event: [ push, tag ]

  backend-finish:
    image: webhippie/golang:edge
    pull: true
    environment:
      - CGO_ENABLED=0
      - GOPATH=/srv/app
      - TAGS=
    commands:
      - make release-copy release-check
    when:
      event: [ push, tag ]

  docker-amd64:
    image: plugins/docker:17.05
    pull: true
    group: docker
    secrets: [ docker_username, docker_password ]
    repo: tboerger/oauth2-proxy
    tags: [ latest ]
    dry_run: true
    when:
      event: [ pull_request ]

  docker-amd64:
    image: plugins/docker:17.05
    pull: true
    group: docker
    secrets: [ docker_username, docker_password ]
    repo: tboerger/oauth2-proxy
    auto_tag: true
    auto_tag_suffix: amd64
    when:
      event: [ push, tag ]

  docker-i386:
    image: plugins/docker:17.05
    pull: true
    group: docker
    secrets: [ docker_username, docker_password ]
    repo: tboerger/oauth2-proxy
    dockerfile: Dockerfile.i386
    auto_tag: true
    auto_tag_suffix: i386
    when:
      event: [ push, tag ]

  docker-arm64:
    image: plugins/docker:17.05
    pull: true
    group: docker
    secrets: [ docker_username, docker_password ]
    repo: tboerger/oauth2-proxy
    dockerfile: Dockerfile.arm64
    auto_tag: true
    auto_tag_suffix: arm64
    when:
      event: [ push, tag ]

  docker-arm:
    image: plugins/docker:17.05
    pull: true
    group: docker
    secrets: [ docker_username, docker_password ]
    repo: tboerger/oauth2-proxy
    dockerfile: Dockerfile.arm
    auto_tag: true
    auto_tag_suffix: arm
    when:
      event: [ push, tag ]

  docker-manifests:
    image: plugins/manifest:1
    pull: true
    secrets: [ docker_username, docker_password ]
    spec: manifest.yml
    auto_tag: true
    ignore_missing: true
    when:
      event: [ push, tag ]

  docker-microbadger:
    image: plugins/webhook:1
    pull: true
    secrets:
      - source: microbadger_token
        target: webhook_urls
    when:
      event: [ push, tag ]

  cache-rebuild:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    rebuild: true
    mount:
      - _tools
      - vendor
      - node_modules
    when:
      local: false
      event: [ push ]

  cache-flush:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    flush: true
    flush_age: 14
    when:
      local: false
      event: [ push ]

  docs-build:
    image: webhippie/hugo:latest
    pull: true
    commands:
      - make docs
    when:
      local: false
      event: [ push ]

  docs-publish:
    image: plugins/gh-pages:1
    pull: true
    secrets: [ github_username, github_password ]
    pages_directory: docs/public/
    temporary_base: tmp/
    when:
      local: false
      event: [ push ]

  archive-release:
    image: plugins/s3:1
    pull: true
    secrets: [ s3_endpoint, aws_access_key_id, aws_secret_access_key, s3_bucket ]
    source: dist/release/*
    target: /misc/oauth2-proxy/master
    strip_prefix: dist/release/
    path_style: true
    when:
      event: [ push ]

  archive-release:
    image: plugins/s3:1
    pull: true
    secrets: [ s3_endpoint, aws_access_key_id, aws_secret_access_key, s3_bucket ]
    source: dist/release/*
    target: /misc/oauth2-proxy/${DRONE_TAG##v}
    strip_prefix: dist/release/
    path_style: true
    when:
      event: [ tag ]

  github-release:
    image: plugins/github-release:1
    pull: true
    secrets: [ github_token ]
    files:
      - dist/release/*
    when:
      event: [ tag ]
      branch: master

  notify-matrix:
    image: plugins/matrix:1
    pull: true
    secrets: [ matrix_roomid, matrix_username, matrix_password ]
    when:
      local: false
      event: [ push, tag ]
      status: [ changed, failure ]
